name: Deploy ACASA ERP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Prepare project (remove heavy folders)
      run: |
        rm -rf backend/node_modules
        rm -rf frontend/node_modules       # Mudei de frontend-vue para frontend
        rm -rf frontend/dist               # Mudei de frontend-vue para frontend
        rm -rf .git
        rm -rf .github

    - name: Upload project to server
      run: |
        # Usei o IP que você mandou, mas se tiver nos secrets, pode usar ${{ secrets.HOST }}
        ssh -o StrictHostKeyChecking=no ec2-user@54.164.55.32 "rm -rf ~/acasa-erp"
        scp -o StrictHostKeyChecking=no -r . ec2-user@54.164.55.32:~/acasa-erp

    - name: Build backend and restart PM2
      run: |
        ssh ec2-user@54.164.55.32 "cd ~/acasa-erp/backend && npm install && pm2 restart all"

    - name: Build frontend
      run: |
        # AQUI É IMPORTANTE: O caminho mudou para ~/acasa-erp/frontend
        ssh ec2-user@54.164.55.32 "cd ~/acasa-erp/frontend && npm install && npm run build"

    - name: Deploy frontend to NGINX
      run: |
        # Caminhos novos no servidor: /var/www/frontend
        ssh ec2-user@54.164.55.32 "sudo rm -rf /var/www/frontend/*"
        ssh ec2-user@54.164.55.32 "sudo cp -r ~/acasa-erp/frontend/dist/* /var/www/frontend/"