name: Deploy ACASA ERP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Upload project to server
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.164.55.32 "rm -rf ~/acasa-erp"
        scp -o StrictHostKeyChecking=no -r . ec2-user@54.164.55.32:~/acasa-erp

    - name: Build backend and restart PM2
      run: |
        ssh ec2-user@54.164.55.32 "cd ~/acasa-erp/backend && npm install && pm2 restart all"

    - name: Build frontend
      run: |
        ssh ec2-user@54.164.55.32 "cd ~/acasa-erp/frontend-vue && npm install && npm run build"

    - name: Deploy frontend to NGINX
      run: |
        ssh ec2-user@54.164.55.32 "sudo rm -rf /var/www/acasa-frontend/*"
        ssh ec2-user@54.164.55.32 "sudo cp -r ~/acasa-erp/frontend-vue/dist/* /var/www/acasa-frontend/"

